### ISSUE TITLE
No module named 'timm'

### ISSUE THREAD

**Issue by AstraMousavi** [shengli666666/WaveletFormerNet#2]
I followed the instruction for running the test.py but I am getting the following error. 
 
 WaveletFormerNet-main % python test.py --task ohaze --input_dir datasets/hazy
Traceback (most recent call last):
  File "WaveletFormerNet-main/test.py", line 4, in <module>
    from models.DwtFormer import DwtFormer
  File "WaveletFormerNet-main/models/DwtFormer.py", line 6, in <module>
    from timm.models.layers import to_2tuple, trunc_normal_
ModuleNotFoundError: No module named 'timm'

**Comment by fengchengtian** [comment]
你可以用anaconda prompt进入虚拟环境再pip install timm
